import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <Link href="/" className="bg-amber-800 text-amber-50 px-5 py-3 my-5 mx-2 inline-block">Home</Link>
          <Link href="/articles" className="bg-amber-800 text-amber-50 px-5 py-3 mx-2 inline-block">Articles</Link>
          <Link href="/posts" className="bg-amber-800 text-amber-50 px-5 py-3 mx-2 inline-block">Posts</Link>
        </nav>
        <div className="children ml-4">
          {children}
        </div>
      </body>
    </html>
  );
}
